#!/usr/bin/env bash
# Install Nginx with the following configurations:
# Listens on port 80
# Returns a page containing "ello World!" when queried
# at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

# Allow nginx on port 80
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "ello World!" > /var/www/html/index.nginx-debian.html

# Restart nginx
sudo service nginx restart
