#!/usr/bin/env bash
# Display content of the file /etc/passwd
# 	Display only:
#		- username
#		- user id
#		- Home directory path for the user

while read -r passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
